######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
# Comment these back in if you want to replace the text that is there now.
# logo_on_white: "img/logo-b.svg"
# logo_on_black: "img/logo-w.svg"
custom_js: []
custom_css: []

######################## custom config ####################
subtitle: "UX designer and strategist"
### default social share image (can also be set per lang) ###
images: ["img/social-share.png"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: false

# You can add additional social links as needed (eg, bluesky: "bsky.social")
# To add a new svg icon, stick it in /static/img/social-icons with the same key (eg, bluesky.svg)
show_social_icons: false
social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: ""
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/in/outerpress/"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""
  gmail: "mailto:parusso@gmail.com"

# Makes the header sticky on tall screens
sticky_header: false
# Enable search in header UI
show_search: false
